"use client";

import {
    Activity,
    Anchor,
    Axe,
    AudioWaveform,
    Bug,
    ChevronsRight,
    Cloud,
    CloudLightning,
    CloudRain,
    Crosshair,
    Droplets,
    Dumbbell,
    EyeOff,
    Fan,
    FlaskConical,
    Flame,
    FlameKindling,
    Footprints,
    Gavel,
    Hammer,
    Heart,
    HeartHandshake,
    HeartPulse,
    Leaf,
    Link,
    Megaphone,
    MicVocal,
    MoveDiagonal,
    MoveUpRight,
    Music,
    Music2,
    Shield,
    ShieldAlert,
    ShieldPlus,
    Skull,
    Snail,
    Snowflake,
    Sparkles,
    Sprout,
    Star,
    Sun,
    Sword,
    Target,
    Trees,
    TriangleAlert,
    Undo2,
    WandSparkles,
    Wind,
    Zap,
    type LucideIcon,
} from "lucide-react";

/** Nombres de icono lucide que usa el catalogo (frontend/lib/mobaCatalog.generated.json) → componente. */
const ICONS: Record<string, LucideIcon> = {
    activity: Activity,
    anchor: Anchor,
    axe: Axe,
    "audio-waveform": AudioWaveform,
    bug: Bug,
    "chevrons-right": ChevronsRight,
    cloud: Cloud,
    "cloud-lightning": CloudLightning,
    "cloud-rain": CloudRain,
    crosshair: Crosshair,
    droplets: Droplets,
    dumbbell: Dumbbell,
    "eye-off": EyeOff,
    fan: Fan,
    flame: Flame,
    "flame-kindling": FlameKindling,
    "flask-conical": FlaskConical,
    footprints: Footprints,
    gavel: Gavel,
    hammer: Hammer,
    heart: Heart,
    "heart-handshake": HeartHandshake,
    "heart-pulse": HeartPulse,
    leaf: Leaf,
    link: Link,
    megaphone: Megaphone,
    "mic-vocal": MicVocal,
    "move-diagonal": MoveDiagonal,
    "move-up-right": MoveUpRight,
    music: Music,
    "music-2": Music2,
    shield: Shield,
    "shield-alert": ShieldAlert,
    "shield-plus": ShieldPlus,
    skull: Skull,
    snail: Snail,
    snowflake: Snowflake,
    sparkles: Sparkles,
    sprout: Sprout,
    sun: Sun,
    sword: Sword,
    target: Target,
    trees: Trees,
    "triangle-alert": TriangleAlert,
    "undo-2": Undo2,
    "wand-sparkles": WandSparkles,
    wind: Wind,
    zap: Zap,
};

export function AbilityIcon({ name, size = 28, className }: { name?: string; size?: number; className?: string }) {
    // "meteor" no existe en esta version de lucide: se usa una estrella fugaz generica.
    const Icon = (name ? ICONS[name] : undefined) ?? Star;

    return <Icon size={size} strokeWidth={1.8} className={className} aria-hidden />;
}
